In [1]:
# 1. a.	Develop a Class in Python called Dense_Layer (included in the submitted notebook).

#a)	(10 points) A function to setup/accept the inputs and weights
#b)	(10 points) A function to perform the weighted sum + bias
#c)	(15 points) A function to perform the selected activation function
#d)	(15 points) A function to calculate the loss (predicted output vs target output)

import numpy as np

class Dense_Layer:

    def __init__(self): #setup/accept inputs and weights
        
        self.inputs = None
        self.weights = None
        self.bias = None
        self.output = None
        

    def summation(self, inputs, weights, bias): #perform weighted sum + bias

        weights_transposed = [list(row) for row in zip(*weights)]
        result= []

        for i in range(len(weights_transposed)):
            sum_val = 0
            for j in range(len(inputs)):
                sum_val += weights_transposed[i][j] * inputs [j][0]
            sum_val += bias[i][0]
            result.append([sum_val])

        return np.array(result)
        
    
    def activation(self, z, func): #for activation function

        z = np.array(z)
        if func == "relu":
            self.output = np.maximum(0,z)
        elif func == "sigmoid":
            self.output = 1/(1 + np.exp(-z))
        elif func == "softmax":
            z_arr = np.array(z).reshape(-1)
            exp_values = np.exp(z_arr - np.max(z_arr))
            soft = exp_values/ np.sum(exp_values)
            self.output = soft.reshape((-1,1))
        else:
            raise ValueError("Unsupported activation function.")
        return self.output

    def loss_function(self, y_target): # for loss function

        y_target = np.array(y_target)
        y_pred = np.array(self.output)

        lf = 0.5 * np.sum((y_target - y_pred) ** 2)
        return lf

In [2]:
#2. a Iris dataset - determining what class the following inputs are
# by calculatingh the output, given the neural network configurations:

#First Hidden Layer

from pprint import pprint

z_one = 0.00

inputs = [
    [5.1],
    [3.5],
    [1.4],
    [0.2]
]

weights_one = [
    [ 0.2, 0.5, -0.4 ],
    [ 0.1, -0.2, 0.4],
    [-0.4, 0.3, 0.2],
    [0.6, -0.1, 0.5]
]

bias_one = [
    [3.0],
    [-2.1],
    [0.6]
]

target_outputs = [
    [0.7],
    [0.2],
    [0.1]
]

#calculating z and activation function values

layer_one = Dense_Layer()

z_one = layer_one.summation(inputs, weights_one, bias_one)
output_one = layer_one.activation(z_one, "relu")

#printing results

print(f"Inputs(X) of first hidden layer are:\n{np.array(inputs)}")
print("                                  \n")
print(f"Weights(W) of first hidden layer are: \n{np.array(weights_one)}")
print("                                  \n")
print(f"bias(B) of first hidden layer are: \n{np.array(bias_one)}")
print("                                  \n")
print(f"Value of z for first hidden layer is: \n{z_one}")
print("                                  \n")
print(f"Output of Hidden layer one is: \n{output_one}")
print("                                  \n")


#Second Hidden Layer

inputs_two = output_one

weights_two = [
    [ 0.3, -0.5],
    [ 0.7, 0.2],
    [-0.6, 0.4]
]

bias_two = [
    [4.3],
    [6.4]
]

layer_two = Dense_Layer()

z_two = layer_two.summation(inputs_two, weights_two, bias_two)
output_two = layer_two.activation(z_two, "sigmoid")

print(f"Inputs(X) of second hidden layer are:\n{np.array(inputs_two)}")
print("                                  \n")
print(f"Weights(W) of second hidden layer are: \n{np.array(weights_two)}")
print("                                  \n")
print(f"bias(B) of second hidden layer are: \n{np.array(bias_two)}")
print("                                  \n")
print(f"Value of z for second hidden layer is: \n{z_two}")
print("                                  \n")
print(f"Output of Hidden layer two is: \n{output_two}")
print("                                  \n")

#Last Layer

inputs_three = output_two

weights_three = [
    [ 0.5, -0.3, 0.8],
    [ -0.2, 0.6, -0.4]
]

bias_three = [
    [-1.5],
    [2.1],
    [-3.3]
]

layer_three = Dense_Layer()

z_three = layer_three.summation(inputs_three, weights_three, bias_three)
output_three = layer_three.activation(z_three, "softmax")

print(f"Inputs(X) of last layer are:\n{np.array(inputs_three)}")
print("                                  \n")
print(f"Weights(W) of last layer are: \n{np.array(weights_three)}")
print("                                  \n")
print(f"bias(B) of last layer are: \n{np.array(bias_three)}")
print("                                  \n")
print(f"Value of z for last layer is: \n{z_three}")
print("                                  \n")
print(f"Output of last layer is: \n{output_three}")
print("                                  \n")

#calculating loss function

loss = layer_three.loss_function(target_outputs)

#predicting class of Iris
predicted = np.argmax(output_three)

iris_classes = ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]
predicted_class = iris_classes[predicted]

print(f"Loss function = {loss}")
print("                                  \n")
print(f"Class is likely {predicted_class}")


Inputs(X) of first hidden layer are:
[[5.1]
 [3.5]
 [1.4]
 [0.2]]
                                  

Weights(W) of first hidden layer are: 
[[ 0.2  0.5 -0.4]
 [ 0.1 -0.2  0.4]
 [-0.4  0.3  0.2]
 [ 0.6 -0.1  0.5]]
                                  

bias(B) of first hidden layer are: 
[[ 3. ]
 [-2.1]
 [ 0.6]]
                                  

Value of z for first hidden layer is: 
[[3.93]
 [0.15]
 [0.34]]
                                  

Output of Hidden layer one is: 
[[3.93]
 [0.15]
 [0.34]]
                                  

Inputs(X) of second hidden layer are:
[[3.93]
 [0.15]
 [0.34]]
                                  

Weights(W) of second hidden layer are: 
[[ 0.3 -0.5]
 [ 0.7  0.2]
 [-0.6  0.4]]
                                  

bias(B) of second hidden layer are: 
[[4.3]
 [6.4]]
                                  

Value of z for second hidden layer is: 
[[5.38 ]
 [4.601]]
                                  

Output of Hidden layer two is: 
[[0.99541331]
 [0.99005805]]
 

In [3]:
# 2. b)Given the following inputs from the Breast Cancer Dataset, 
#      using three features: Mean Radius, Mean Texture, and Mean Smoothness, 
#      determine whether the tumor is Benign (0) or Malignant (1) 
#      by calculating the network outputs step by step, given the following 
#      neural network configuration:

# Step 0: Inputs and Target
inputs = [
    [14.1],
    [20.3],
    [0.095]
]

target_output = [1]

# First Hidden Layer
weights_one = [
    [0.5, -0.3, 0.8],
    [0.2, 0.4, -0.6],
    [-0.7, 0.9, 0.1]
]

bias_one = [
    [0.3],
    [-0.5],
    [0.6]
]

layer_one = Dense_Layer()
z_one = layer_one.summation(inputs, weights_one, bias_one)
output_one = layer_one.activation(z_one, "relu")

print(f"Inputs(X) of first hidden layer are:\n{np.array(inputs)}\n")
print(f"Weights(W) of first hidden layer are: \n{np.array(weights_one)}\n")
print(f"Bias(B) of first hidden layer are: \n{np.array(bias_one)}\n")
print(f"Value of z for first hidden layer is: \n{z_one}\n")
print(f"Output of Hidden layer one is: \n{output_one}\n")

# Second Hidden Layer

inputs_two = output_one

weights_two = [ 
    [0.6, -0.3], 
    [-0.2, 0.5], 
    [0.4, 0.7] 
]

bias_two = [ [0.1], [-0.8] ]

layer_two = Dense_Layer()

z_two = layer_two.summation(inputs_two, weights_two, bias_two)
output_two = layer_two.activation(z_two, "sigmoid")

print(f"Inputs(X) of second hidden layer are:\n{np.array(inputs_two)}\n")
print(f"Weights(W) of second hidden layer are: \n{np.array(weights_two)}\n")
print(f"Bias(B) of second hidden layer are: \n{np.array(bias_two)}\n")
print(f"Value of z for second hidden layer is: \n{z_two}\n")
print(f"Output of Hidden layer two is: \n{output_two}\n")


# Last Layer

inputs_three = output_two

weights_three = [
    [0.7],
    [-0.5]
]
bias_three = [
    [0.2]
]

layer_three = Dense_Layer()

z_three = layer_three.summation(inputs_three, weights_three, bias_three)
output_three = layer_three.activation(z_three, "sigmoid")  # final output

print(f"Inputs(X) of output layer are:\n{np.array(inputs_three)}\n")
print(f"Weights(W) of output layer are: \n{np.array(weights_three)}\n")
print(f"Bias(B) of output layer are: \n{np.array(bias_three)}\n")
print(f"Value of z for output layer is: \n{z_three}\n")
print(f"Output of last layer is: \n{output_three}\n")

# calculating loss function
loss = layer_three.loss_function(target_output)
print(f"Loss function = {loss}\n")

# Predicted Class and Tumor Type
predicted_value = output_three[0][0]
predicted_class = 1 if output_three[0][0] >= 0.5 else 0
tumor_type = "Malignant" if predicted_class == 1 else "Benign"

print(f"Tumor Type: ({predicted_class}) {tumor_type}")

Inputs(X) of first hidden layer are:
[[14.1  ]
 [20.3  ]
 [ 0.095]]

Weights(W) of first hidden layer are: 
[[ 0.5 -0.3  0.8]
 [ 0.2  0.4 -0.6]
 [-0.7  0.9  0.1]]

Bias(B) of first hidden layer are: 
[[ 0.3]
 [-0.5]
 [ 0.6]]

Value of z for first hidden layer is: 
[[11.3435]
 [ 3.4755]
 [-0.2905]]

Output of Hidden layer one is: 
[[11.3435]
 [ 3.4755]
 [ 0.    ]]

Inputs(X) of second hidden layer are:
[[11.3435]
 [ 3.4755]
 [ 0.    ]]

Weights(W) of second hidden layer are: 
[[ 0.6 -0.3]
 [-0.2  0.5]
 [ 0.4  0.7]]

Bias(B) of second hidden layer are: 
[[ 0.1]
 [-0.8]]

Value of z for second hidden layer is: 
[[ 6.211 ]
 [-2.4653]]

Output of Hidden layer two is: 
[[0.99799679]
 [0.07832686]]

Inputs(X) of output layer are:
[[0.99799679]
 [0.07832686]]

Weights(W) of output layer are: 
[[ 0.7]
 [-0.5]]

Bias(B) of output layer are: 
[[0.2]]

Value of z for output layer is: 
[[0.85943432]]

Output of last layer is: 
[[0.70254245]]

Loss function = 0.04424049571307605

Tumor Type: (1) Mal