# Exercise for Unit 2

**Name:** MYRRHEA BELLE B. JUNSAY

**Date:** SEPTEMBER 12, 2025

**Year and Section:** BSCS 3A AI

## 1. Choose task

**Chosen task:** 

a.	Develop a Class in Python called Dense_Layer (included in the submitted notebook). The chosen task should have the following functions:

a) A function to setup/accept the inputs and weights

b) A function to perform the weighted sum + bias

c) A function to perform the selected activation function

d) A function to calculate the loss (predicted output vs target output)



In [1]:
import numpy as np

# d. A function to setup/accept the inputs and weights
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# c. A function to calculate the loss
def categorical_cross_entropy(y_pred, y_true):
    y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
    loss = -np.sum(y_true * np.log(y_pred_clipped))
    return loss

def binary_cross_entropy(y_pred, y_true):
    y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
    loss = -(y_true * np.log(y_pred_clipped) + (1 - y_true) * np.log(1 - y_pred_clipped))
    return np.mean(loss)


# Dense Layer Class
class Dense_Layer:
    
    # a. A function to setup/accept the inputs and weights
    def __init__(self, weights, biases):
        self.weights = weights
        self.biases = biases
        self.output = None

    # b. A function to perform the weighted sum + bias
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        return self.output

## 2. Problem Set

**Chosen problem set:** 

a) Given the inputs from the Iris Dataset, using the sepal length, sepal width, petal length and petal width, determine what class (Iris-setosa, Iris-versicolor, and Iris-virginica) the inputs are by calculating the output with the given the neural network configurations.

In [7]:
print("Iris Dataset Calculation\n")

# Input features
X_iris = np.array([[5.1, 3.5, 1.4, 0.2]])
# Target output 
target_iris = np.array([[0.7, 0.2, 0.1]])

# Layer 1
W1_iris = np.array([[0.2, 0.5, -0.3], [0.1, -0.2, 0.4], [-0.4, 0.3, 0.2], [0.6, -0.1, 0.5]])
B1_iris = np.array([[3.0, -2.1, 0.6]])
activation1_iris = relu

# Layer 2
W2_iris = np.array([[0.3, -0.5], [0.7, 0.2], [-0.6, 0.4]])
B2_iris = np.array([[4.3, 6.4]])
activation2_iris = sigmoid

# Layer 3 (Output) 
W3_iris = np.array([[0.5, -0.3, 0.8], [-0.2, 0.6, -0.4]])
B3_iris = np.array([[-1.5, 2.1, -3.3]])
activation3_iris = softmax

# Hidden Layer 1
layer1 = Dense_Layer(W1_iris, B1_iris)
output1_raw = layer1.forward(X_iris)
output1_activated = activation1_iris(output1_raw)
print(f"Hidden Layer 1 (Output): \n{output1_activated}\n")

# Hidden Layer 2
layer2 = Dense_Layer(W2_iris, B2_iris)
output2_raw = layer2.forward(output1_activated)
output2_activated = activation2_iris(output2_raw)

print(f"Hidden Layer 2 (Output): \n{output2_activated}\n")

# Output Layer
layer3 = Dense_Layer(W3_iris, B3_iris)
output3_raw = layer3.forward(output2_activated)
final_output_iris = activation3_iris(output3_raw)

print(f"Final Predicted Output: \n{final_output_iris}\n")

# Loss Calculation
loss_iris = categorical_cross_entropy(final_output_iris, target_iris)
print(f"Loss: {loss_iris:.4f}")

predicted_class_index = np.argmax(final_output_iris)
classes = ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]
print(f"\nPredicted Class: {classes[predicted_class_index]}")

Iris Dataset Calculation

Hidden Layer 1 (Output): 
[[3.93 0.15 0.85]]

Hidden Layer 2 (Output): 
[[0.99378157 0.99187781]]

Final Predicted Output: 
[[0.0265075  0.96865119 0.00484132]]

Loss: 3.0807

Predicted Class: Iris-versicolor


**Chosen problem set:** 

b) Given the inputs from the Breast Cancer Dataset, using three features: Mean Radius, Mean Texture, and Mean Smoothness, determine whether the tumor is Benign (0) or Malignant (1) by calculating the network outputs step by step, given the neural network configuration.

In [6]:
print("Breast Cancer Dataset Calculation\n")

X_cancer = np.array([[14.1, 20.3, 0.095]])

# Target output
target_cancer = 1 # Malignant

# Layer 1
W1_cancer = np.array([[0.5, -0.3, 0.8], [0.2, 0.4, -0.6], [-0.7, 0.9, 0.1]])
B1_cancer = np.array([[0.3, -0.5, 0.6]])
activation1_cancer = relu

# Layer 2
W2_cancer = np.array([[0.6, -0.2], [0.4, -0.3], [0.5, 0.7]])
B2_cancer = np.array([[0.1, -0.8]])
activation2_cancer = sigmoid

# Output
W3_cancer = np.array([[0.7], [-0.5]]) 
B3_cancer = np.array([[0.2]])
activation3_cancer = sigmoid

# Hidden Layer 1
layer1_cancer = Dense_Layer(W1_cancer, B1_cancer)
output1_raw_cancer = layer1_cancer.forward(X_cancer)
output1_activated_cancer = activation1_cancer(output1_raw_cancer)
print(f"Hidden Layer 1 (Output): \n{output1_activated_cancer}\n")

# Hidden Layer 2
layer2_cancer = Dense_Layer(W2_cancer, B2_cancer)
output2_raw_cancer = layer2_cancer.forward(output1_activated_cancer)
output2_activated_cancer = activation2_cancer(output2_raw_cancer)
print(f"Hidden Layer 2 (Output): \n{output2_activated_cancer}\n")

# Output Layer
layer3_cancer = Dense_Layer(W3_cancer, B3_cancer)
output3_raw_cancer = layer3_cancer.forward(output2_activated_cancer)
final_output_cancer = activation3_cancer(output3_raw_cancer)
print(f"Final Predicted Output: \n{final_output_cancer}\n")

# Loss Calculation
loss_cancer = binary_cross_entropy(final_output_cancer, target_cancer)
print(f"Loss: {loss_cancer:.4f}") 

# Determine predicted class
predicted_class = "Malignant (1)" if final_output_cancer[0][0] >= 0.5 else "Benign (0)"
print(f"\nPredicted Class: {predicted_class}")

Breast Cancer Dataset Calculation

Hidden Layer 1 (Output): 
[[11.3435  3.4755  0.    ]]

Hidden Layer 2 (Output): 
[[0.99975062 0.01612148]]

Final Predicted Output: 
[[0.70925421]]

Loss: 0.3435

Predicted Class: Malignant (1)
