In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [6]:
# Load and preprocess MNIST dataset
# the MNIST dataset is a set of 70,000 small images of handwritten digits
# It is needed to be downloaded first

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape((x_train.shape[0], 28*28)).astype('float32') / 255 # Why 255?
x_test = x_test.reshape((x_test.shape[0], 28*28)).astype('float32') / 255

In [7]:
# One-hot encode the labels
# You can check the shape and content of y_train and y_test before and after this step
print("Before one-hot encoding:", y_train[:5])

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print("After one-hot encoding:", y_train[:5])

Before one-hot encoding: [5 0 4 1 9]
After one-hot encoding: [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# Define the model
# Sequential model is a linear stack of layers
model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

c:\Users\msi msi\OneDrive\Documents\Python\Artificial Neural Networks\.venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [10]:
# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9302 - loss: 0.2396 - val_accuracy: 0.9644 - val_loss: 0.1151
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9687 - loss: 0.1017 - val_accuracy: 0.9695 - val_loss: 0.0967
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9779 - loss: 0.0706 - val_accuracy: 0.9766 - val_loss: 0.0742
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9827 - loss: 0.0534 - val_accuracy: 0.9764 - val_loss: 0.0811
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9858 - loss: 0.0434 - val_accuracy: 0.9770 - val_loss: 0.0764
