INSTALL THE FOLLOWING PYTHON PACKAGES FIRST BEFORE RUNNING THE PROGRAM

1) Numpy
2) NNFS - for the Spiral dataset
3) scikit-learn - for the iris dataset

In [12]:
# Library imports
import numpy as np

Create classes for modularity

In [13]:
# Hidden Layers
# Dense
class Layer_Dense:
    # Layer initialization
    # randomly initialize weights and set biases to zero
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))


    # Forward pass
    def forward(self, inputs):
        # Remember the input values
        self.inputs = inputs
        # Calculate the output values from inputs, weight and biases
        self.output = np.dot(inputs, self.weights) + self.biases

    # Backward pass/Backpropagation
    def backward(self, dvalues):
        # Gradients on parameters:
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
        # Gradient on values
        self.dinputs = np.dot(dvalues, self.weights.T)


In [14]:
# Activation Functions
# Included here are the functions for both the forward and backward pass

# Linear
class ActivationLinear:
    def forward(self, inputs):
        self.inputs = inputs
        self.output = inputs

    def backward(self, dvalues):
        self.dinputs = dvalues.copy()

# Sigmoid
class ActivationSigmoid:
    def forward(self, inputs):
        self.inputs = inputs
        self.output = 1 / (1 + np.exp(-inputs))

    def backward(self, dvalues):
        self.dinputs = dvalues * (self.output * (1 - self.output))

# TanH
class ActivationTanH:
    def forward(self, inputs):
        self.inputs = inputs
        self.output = np.tanh(inputs)

    def backward(self, dvalues):
        self.dinputs = dvalues * (1 - self.output ** 2)

# ReLU
class Activation_ReLU:
    # Forward pass
    def forward(self, inputs):
        # Remember the input values
        self.inputs = inputs
        # Calculate the output values from inputs
        self.output = np.maximum(0, inputs)

    # Backward pass
    def backward(self, dvalues):
        # Make a copy of the original values first
        self.dinputs = dvalues.copy()
    
        # Zero gradient where input values were negative
        self.dinputs[self.inputs <= 0] = 0

# Softmax
class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
        # Remember the inputs values
        self.inputs = inputs

        # Get the unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

    # Backward pass
    def backward(self, dvalues):
        # Create uninitialized array
        self.dinputs = np.empty_like(dvalues)

        # Enumerate outputs and gradients
        for index, (single_output, single_dvalues) in enumerate(zip(self.output, dvalues)):

            # Flatten output array
            single_output = single_output.reshape(-1, 1)
            # Calculate Jacobian matrix of the output
            jacobian_matrix = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            # Calculate the sample-wise gradient
            # and add it to the array of sample gradients
            self.dinputs[index] = np.dot(jacobian_matrix, single_dvalues)

In [15]:
# Loss functions

class Loss:
    # Calculate the data and regularization losses
    # Given the model output and grou truth/target values
    def calculate(self, output, y):
        # Calculate sample losses
        sample_losses = self.forward(output, y)
        # Calculate the mean loss
        data_loss = np.mean(sample_losses)
        # Return the mean loss
        return data_loss

# MSE
class Loss_MSE:
    def forward(self, y_pred, y_true):
        # Calculate Mean Squared Error
        return np.mean((y_true - y_pred) ** 2, axis=-1)

    def backward(self, y_pred, y_true):
        # Gradient of MSE loss
        samples = y_true.shape[0]
        outputs = y_true.shape[1]
        self.dinputs = -2 * (y_true - y_pred) / outputs
        # Normalize gradients over samples
        self.dinputs = self.dinputs / samples

# Binary Cross-Entropy
class Loss_BinaryCrossEntropy:
    def forward(self, y_pred, y_true):
        # Clip predictions
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        # Calculate Binary Cross Entropy
        return -(y_true * np.log(y_pred_clipped) + (1 - y_true) * np.log(1 - y_pred_clipped))

    def backward(self, y_pred, y_true):
        # Gradient of BCE loss
        samples = y_true.shape[0]
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        self.dinputs = - (y_true / y_pred_clipped - (1 - y_true) / (1 - y_pred_clipped))
        # Normalize gradients over samples
        self.dinputs = self.dinputs / samples

# Categorical Cross-Entropy
class Loss_CategoricalCrossEntropy(Loss):
    # Forward pass
    def forward(self, y_pred, y_true):
        # Number of samples in a batch
        samples = y_pred.shape[0]

        # Clip data to prevent division by 0
        # Clip both sides to not drag mean towards any value
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        # Probabilities for target values
        # Only if categorical labels
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        # Mask values - only for one-hot encoded labels
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)

        # Losses
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

    # Backward pass
    def backward(self, dvalues, y_true):
        # Number of samples
        samples = len(dvalues)
        # Number of labels in every sample
        # Use the first sample to count them
        labels = len(dvalues[0])

        # Check if labels are sparse, turn them into one-hot vector values
        # the eye function creates a 2D array with ones on the diagonal and zeros elsewhere
        if len(y_true.shape) == 1:
            y_true = np.eye(labels)[y_true]

        # Calculate the gradient
        self.dinputs = -y_true / dvalues
        self.dinputs = self.dinputs / samples


<!-- Star -->

In [16]:
# Start of Optimizers
# Enhanced optimizer supporting learning rate decay, momentum, and Adagrad
class Optimizer_SGD:
    def __init__(self, learning_rate=1.0, decay=0.0, momentum=0.0, optimizer_type="sgd", epsilon=1e-7):
        """
        optimizer_type can be:
            "sgd"       -> Standard Stochastic Gradient Descent (with optional decay)
            "momentum"  -> SGD with Momentum
            "adagrad"   -> Adaptive Gradient (AdaGrad)
        """
        self.learning_rate = learning_rate
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.iterations = 0
        self.momentum = momentum
        self.optimizer_type = optimizer_type.lower()
        self.epsilon = epsilon

    # Call before any parameter updates in an epoch/iteration
    def pre_update_params(self):
        # Apply learning rate decay (before FP/BP)
        if self.decay:
            self.current_learning_rate = self.learning_rate / (1 + self.decay * self.iterations)

    # Update the parameters of a given layer
    def update_params(self, layer):
        # Initialize momentum and cache arrays if not yet created
        if not hasattr(layer, 'weights_momentum'):
            layer.weights_momentum = np.zeros_like(layer.weights)
            layer.biases_momentum = np.zeros_like(layer.biases)
        if not hasattr(layer, 'weights_cache'):
            layer.weights_cache = np.zeros_like(layer.weights)
            layer.biases_cache = np.zeros_like(layer.biases)

        # --- Optimizer logic ---
        if self.optimizer_type == "momentum":
            # SGD with Momentum
            layer.weights_momentum = self.momentum * layer.weights_momentum - self.current_learning_rate * layer.dweights
            layer.biases_momentum = self.momentum * layer.biases_momentum - self.current_learning_rate * layer.dbiases
            layer.weights += layer.weights_momentum
            layer.biases += layer.biases_momentum

        elif self.optimizer_type == "adagrad":
            # Adaptive Gradient (AdaGrad)
            layer.weights_cache += layer.dweights ** 2
            layer.biases_cache += layer.dbiases ** 2
            layer.weights += -self.current_learning_rate * layer.dweights / (np.sqrt(layer.weights_cache) + self.epsilon)
            layer.biases += -self.current_learning_rate * layer.dbiases / (np.sqrt(layer.biases_cache) + self.epsilon)

        else:  # "sgd" (basic)
            # Basic SGD update (with optional learning rate decay)
            layer.weights += -self.current_learning_rate * layer.dweights
            layer.biases += -self.current_learning_rate * layer.dbiases

    # Call after parameter updates to increase iteration count
    def post_update_params(self):
        self.iterations += 1


Use most of the classes to create a functioning neural network, capable of performing a forward and backward pass

We can use a sample dataset from the Spiral module.  

We can also use the IRIS dataset.

In [17]:
# Spiral Data
import nnfs
from nnfs.datasets import spiral_data

# Create the dataset
X, y = spiral_data(samples = 100, classes = 3)

# print(X[:5])
# print(X.shape)
# print(y[:5])
# print(y.shape)

In [18]:
# Iris Dataset
# From the scikit-learn library
# from sklearn.datasets import load_iris
# iris = load_iris()
# X = iris.data # Features
# y = iris.target # Target labels

# print(X[:5])
# print(X.shape)
# print(y[:5])
# print(y.shape)

In [19]:
# Neural Network initialization
# Create a Dense Layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Make sure you check the shape of the features, in order to adjust the input size of the first layer
# dense1 = Layer_Dense(4, 3)

# Create a ReLU activation for the first Dense layer
activation1 = Activation_ReLU()

# Create a 2nd dense layer with 3 input and 3 output values
dense2 = Layer_Dense(3, 3)

# Create a Softmax activation for the 2nd Dense layer
activation2 = Activation_Softmax()

# Create a loss function
loss_function = Loss_CategoricalCrossEntropy()

# Create the optimizer
optimizer = Optimizer_SGD()

PERFORM ONLY 1 PASS

In [20]:
# Training loop: perform forward pass, backpropagation, and update for multiple epochs
epochs = 1000
learning_rate = 1.0

# Choose which optimizer to use: "sgd", "momentum", or "adagrad"
optimizer = Optimizer_SGD(
    learning_rate=learning_rate,
    decay=1e-3,
    momentum=0.9,
    optimizer_type="adagrad"   # change this to "sgd" or "adagrad"
)

# Print which optimizer is active (for clarity in output/screenshots)
print(f"Using optimizer: {optimizer.optimizer_type.upper()}")

loss_history = []
for epoch in range(1, epochs + 1):
    # Pre-update step for optimizer (apply learning rate decay before forward/backward)
    optimizer.pre_update_params()

    # --- Forward pass ---
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    # --- Loss and accuracy ---
    loss = loss_function.calculate(activation2.output, y)
    loss_history.append(loss)
    predictions = np.argmax(activation2.output, axis=1)
    if len(y.shape) == 2:
        y_true = np.argmax(y, axis=1)
    else:
        y_true = y
    accuracy = np.mean(predictions == y_true)

    # Print progress every 100 epochs (and at the first epoch)
    if epoch == 1 or epoch % 100 == 0:
        print(f'Epoch {epoch}/{epochs} - loss: {loss:.4f} - acc: {accuracy:.4f} - lr: {optimizer.current_learning_rate:.6f}')

    # --- Backward pass ---
    loss_function.backward(activation2.output, y)
    dvalues = loss_function.dinputs
    activation2.backward(dvalues)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # --- Update weights and biases ---
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

# After training, print final loss and accuracy
print(f'Final loss: {loss_history[-1]:.4f} - Final acc: {accuracy:.4f}')


Using optimizer: ADAGRAD
Epoch 1/1000 - loss: 1.0986 - acc: 0.3733 - lr: 1.000000
Epoch 100/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.909918
Epoch 200/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.834028
Epoch 300/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.769823
Epoch 400/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.714796
Epoch 500/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.667111
Epoch 600/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.625391
Epoch 700/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.588582
Epoch 800/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.555864
Epoch 900/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.526593
Epoch 1000/1000 - loss: 1.0786 - acc: 0.3833 - lr: 0.500250
Final loss: 1.0786 - Final acc: 0.3833


In [21]:
# Perform a backward pass of our training data
# From loss to 2nd softmax activation
loss_function.backward(activation2.output, y)
dvalues = loss_function.dinputs # Gradient of the loss w.r.t softmax output

print(dvalues.shape)
# print(dvalues)

# From 2nd softmax to 2nd dense layer
activation2.backward(dvalues)
# From 2nd dense layer to 1st ReLU activation
dense2.backward(activation2.dinputs)

# From 1st ReLU activation to 1st dense layer
activation1.backward(dense2.dinputs)
dense1.backward(activation1.dinputs)

(300, 3)


In [22]:
# Check the gradient values of the weights and biases of the established layers
print(dense1.dweights)
print(dense1.dbiases)
print(dense2.dweights)
print(dense2.dbiases)


# Update the weights and biases
optimizer.update_params(dense1)
optimizer.update_params(dense2)

[[ 0.00000000e+00 -1.80046584e-04  0.00000000e+00]
 [ 0.00000000e+00 -7.55630684e-05  0.00000000e+00]]
[[0.         0.00019328 0.        ]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.85497767e-06 -6.58573936e-06  7.30761692e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[[ 2.77363418e-06 -3.39779055e-06  6.24156373e-07]]


Added this line for git to register changes